# Generated by Django 2.2.4 on 2020-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='aims',
            field=models.TextField(default='to provide better foundation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='classScheduling',
            field=models.TextField(default='2-4 days a week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='courseCompletion',
            field=models.TextField(default='mid of August'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='eligibility',
            field=models.CharField(default='for class VII, VIII, IX and X.', max_length=200),
            preserve_default=False,
        ),
    ]
